#!/usr/bin/env node

const { argv } = require('yargs')
  .usage('用法: ./$0 <目錄ID> [options]')
  .example('./$0 1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75', '獲取 https://drive.google.com/drive/folders/1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75 內包含的的所有文件的統計訊息')
  .example('./$0 root -s size -t html -o out.html', '獲取個人盤根目錄統計訊息，結果以HTML表格輸出，根據總大小逆序排列，保存到本目錄下的out.html文件中（不存在則新建，存在則覆蓋）')
  .example('./$0 root -s name -t json -o out.json', '獲取個人盤根目錄統計訊息，結果以JSON格式輸出，根據文件擴展名排序，保存到本目錄下的out.json文件中')
  .example('./$0 root -t all -o all.json', '獲取個人盤根目錄統計訊息，將所有文件訊息（包括文件夾）以JSON格式輸出，保存到本目錄下的all.json文件中')
  .alias('u', 'update')
  .describe('u', '強制從線上獲取訊息(無視是否存在本地緩存)')
  .alias('N', 'not_teamdrive')
  .describe('N', '如果不是團隊盤鏈接，可以加上此參數以提高接口查詢效率，降低延遲。如果要統計的是個人盤且./sa目錄下的service account沒有相關權限，請確保加上此參數以使用個人的auth訊息進行查詢')
  .alias('S', 'service_account')
  .describe('S', '指定使用service account進行統計，前提是必須在sa目錄下放置SA json文件')
  .alias('s', 'sort')
  .describe('s', '統計結果排序方法，可選值 name 或 size，不填則默認根據文件數量逆序排列')
  .alias('t', 'type')
  .describe('t', '統計結果輸出類型，可選值 html/tree/snap/json/all，all表示輸出所有文件json數據，最好搭配 -o 使用。不填則默認輸出命令行表格')
  .alias('o', 'output')
  .describe('o', '統計結果輸出文件，適合搭配 -t 使用')
  .help('h')
  .alias('h', 'help')

const { count, validate_fid } = require('./src/gd')
const [fid] = argv._
if (validate_fid(fid)) {
  const { update, sort, type, output, not_teamdrive, service_account } = argv
  count({ fid, update, sort, type, output, not_teamdrive, service_account }).catch(console.error)
} else {
  console.warn('目錄ID缺失或格式錯誤')
}
