#!/usr/bin/env node

const { argv } = require('yargs')
  .usage('用法: ./$0 <目錄ID> [options]')
  .example('./$0 1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75', '獲取 https://drive.google.com/drive/folders/1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75 內的所有文件信息，並將各文件的md5值和ID存入本地數據庫中')
  .example('./$0 1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75 -s 10mb', '獲取指定目錄的所有文件信息，將不小於10MB大小的文件的md5值和ID存入本地數據庫中')
  .alias('s', 'size')
  .describe('s', '不填默認存儲所有文件的md5記錄，如果設置了這個值，則過濾掉小於這個size的文件，必須以b結尾，比如10mb')
  .alias('u', 'update')
  .describe('u', '強制從線上獲取信息(無視是否存在本地緩存)')
  .alias('N', 'not_teamdrive')
  .describe('N', '如果不是團隊盤鏈接，可以加上此參數以提高接口查詢效率，降低延遲')
  .alias('S', 'service_account')
  .describe('S', '使用service account獲取文件信息，前提是必須在./sa目錄下放置SA json文件')
  .help('h')
  .alias('h', 'help')

const { save_md5, validate_fid } = require('./src/gd')
const [fid] = argv._
if (validate_fid(fid)) {
  const { update, size, not_teamdrive, service_account } = argv
  save_md5({fid, size, not_teamdrive, update, service_account}).catch(console.error)
} else {
  console.warn('目錄ID缺失或格式錯誤')
}
